var OA_output = new Array(); 
OA_output['689'] = '';
OA_output['689'] += "<"+"script src=\"http://tag.contextweb.com/TagPublish/getjs.aspx?action=VIEWAD&cwrun=200&cwadformat=300X600&cwpid=543168&cwwidth=300&cwheight=600&cwpnet=1&cwtagid=213534\"><"+"/script><"+"div id=\'beacon_9167378ac0\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.adip.ly/revive/www/delivery/lg.php?bannerid=704&amp;campaignid=117&amp;zoneid=689&amp;loc=1&amp;referer=http%3A%2F%2Fbeforeitsnews.com%2Fhealth%2F2015%2F05%2Fnever-say-these-4-things-to-parents-with-a-vaccine-injured-child-2572354.html&amp;cb=9167378ac0\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['690'] = '';
OA_output['690'] += "<"+"script type=\'text/javascript\'>\n";
OA_output['690'] += "<"+"!--//<"+"![CDATA[\n";
OA_output['690'] += "document.MAX_ct0 =\'\';\n";
OA_output['690'] += "var m3_u = (location.protocol==\'https:\'?\'https://cas.criteo.com/delivery/ajs.php?\':\'http://cas.criteo.com/delivery/ajs.php?\');\n";
OA_output['690'] += "var m3_r = Math.floor(Math.random()*99999999999);\n";
OA_output['690'] += "document.write (\"<"+"scr\"+\"ipt type=\'text/javascript\' src=\'\"+m3_u);\n";
OA_output['690'] += "document.write (\"zoneid=198894\");document.write(\"&amp;nodis=1\");\n";
OA_output['690'] += "document.write (\'&amp;cb=\' + m3_r);\n";
OA_output['690'] += "if (document.MAX_used != \',\') document.write (\"&amp;exclude=\" + document.MAX_used);\n";
OA_output['690'] += "document.write (document.charset ? \'&amp;charset=\'+document.charset : (document.characterSet ? \'&amp;charset=\'+document.characterSet : \'\'));\n";
OA_output['690'] += "document.write (\"&amp;loc=\" + escape(window.location));\n";
OA_output['690'] += "if (document.referrer) document.write (\"&amp;referer=\" + escape(document.referrer));\n";
OA_output['690'] += "if (document.context) document.write (\"&context=\" + escape(document.context));\n";
OA_output['690'] += "if ((typeof(document.MAX_ct0) != \'undefined\') && (document.MAX_ct0.substring(0,4) == \'http\')) {\n";
OA_output['690'] += "document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));\n";
OA_output['690'] += "}\n";
OA_output['690'] += "if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");\n";
OA_output['690'] += "document.write (\"\'><"+"/scr\"+\"ipt>\");\n";
OA_output['690'] += "//]]>--><"+"/script><"+"div id=\'beacon_dd013398a5\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.adip.ly/revive/www/delivery/lg.php?bannerid=705&amp;campaignid=117&amp;zoneid=690&amp;loc=1&amp;referer=http%3A%2F%2Fbeforeitsnews.com%2Fhealth%2F2015%2F05%2Fnever-say-these-4-things-to-parents-with-a-vaccine-injured-child-2572354.html&amp;cb=dd013398a5\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['691'] = '';
OA_output['691'] += "<"+"script type=\'text/javascript\'>\n";
OA_output['691'] += "<"+"!--//<"+"![CDATA[\n";
OA_output['691'] += "document.MAX_ct0 =\'\';\n";
OA_output['691'] += "var m3_u = (location.protocol==\'https:\'?\'https://cas.criteo.com/delivery/ajs.php?\':\'http://cas.criteo.com/delivery/ajs.php?\');\n";
OA_output['691'] += "var m3_r = Math.floor(Math.random()*99999999999);\n";
OA_output['691'] += "document.write (\"<"+"scr\"+\"ipt type=\'text/javascript\' src=\'\"+m3_u);\n";
OA_output['691'] += "document.write (\"zoneid=198894\");document.write(\"&amp;nodis=1\");\n";
OA_output['691'] += "document.write (\'&amp;cb=\' + m3_r);\n";
OA_output['691'] += "if (document.MAX_used != \',\') document.write (\"&amp;exclude=\" + document.MAX_used);\n";
OA_output['691'] += "document.write (document.charset ? \'&amp;charset=\'+document.charset : (document.characterSet ? \'&amp;charset=\'+document.characterSet : \'\'));\n";
OA_output['691'] += "document.write (\"&amp;loc=\" + escape(window.location));\n";
OA_output['691'] += "if (document.referrer) document.write (\"&amp;referer=\" + escape(document.referrer));\n";
OA_output['691'] += "if (document.context) document.write (\"&context=\" + escape(document.context));\n";
OA_output['691'] += "if ((typeof(document.MAX_ct0) != \'undefined\') && (document.MAX_ct0.substring(0,4) == \'http\')) {\n";
OA_output['691'] += "document.write (\"&amp;ct0=\" + escape(document.MAX_ct0));\n";
OA_output['691'] += "}\n";
OA_output['691'] += "if (document.mmm_fo) document.write (\"&amp;mmm_fo=1\");\n";
OA_output['691'] += "document.write (\"\'><"+"/scr\"+\"ipt>\");\n";
OA_output['691'] += "//]]>--><"+"/script><"+"div id=\'beacon_af0157e82a\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.adip.ly/revive/www/delivery/lg.php?bannerid=706&amp;campaignid=117&amp;zoneid=691&amp;loc=1&amp;referer=http%3A%2F%2Fbeforeitsnews.com%2Fhealth%2F2015%2F05%2Fnever-say-these-4-things-to-parents-with-a-vaccine-injured-child-2572354.html&amp;cb=af0157e82a\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['692'] = '';
OA_output['692'] += "<"+"script src=\"http://tag.contextweb.com/TagPublish/getjs.aspx?action=VIEWAD&cwrun=200&cwadformat=120X600&cwpid=543168&cwwidth=120&cwheight=600&cwpnet=1&cwtagid=213533\"><"+"/script><"+"div id=\'beacon_5b089a50b5\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'http://rev.adip.ly/revive/www/delivery/lg.php?bannerid=707&amp;campaignid=117&amp;zoneid=692&amp;loc=1&amp;referer=http%3A%2F%2Fbeforeitsnews.com%2Fhealth%2F2015%2F05%2Fnever-say-these-4-things-to-parents-with-a-vaccine-injured-child-2572354.html&amp;cb=5b089a50b5\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
